image: docker:latest
stages:
  - build
  - deploy

java-build:
  stage: build
  variables:
    SHA: $(git rev-parse HEAD)
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  image: maven:3.6.3-jdk-8
  services:
    - postgres
    - redis
  script:
    - export $(cat .env.ci.gitlab | xargs)
    - mvn -ntp clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - java -Dspring.profiles.active=integration-test -jar ./migrator/target/application.jar
    - mvn -ntp install -DskipTests=true
  artifacts:
    paths:
      - common/target/
      - importer/target/
      - migrator/target/

react-build:
  stage: build
  variables:
    SHA: $(git rev-parse HEAD)
  image: node
  cache:
    paths:
      - react-app/node_modules/
  script:
    - cd react-app
    - yarn install
    - yarn test:coverage
  artifacts:
    paths:
      - build/

deployment:
  stage: deploy
  script:
    - pwd
    - cd importer/target
    - ls -la
