language: java
os: linux
env:
  global:
    - SHA=$(git rev-parse HEAD)
    # deactivate prompts in gcloud
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
jobs:
  include:
    - stage: test
      language: java
      services:
        - postgresql
        - redis
        - docker
      cache:
        directories:
          - "$HOME/.cache"
      install:
        # load ci env variables
        - export $(cat .env.ci | xargs)
        # setup database and schema
        - psql -c 'drop database if exists dwhtest;' -U postgres
        - psql -c 'create database dwhtest;' -U postgres
        # build java packages
        - mvn -ntp clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
        # run migrations on test database
        - java -Dspring.profiles.active=integration-test -jar ./migrator/target/application.jar
      script:
        - mvn -ntp install
      after_success:
        - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f common/target/site/jacoco/jacoco.xml -c -F java
        - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f importer/target/site/jacoco/jacoco.xml -c -F java
    - language: node_js
      node_js:
        - 12
      before_script:
        - cd react-app
        - yarn install
      cache:
        directories:
          - "node_modules"
      script:
        - yarn test:coverage
      after_success:
        bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f coverage/coverage-final.json -c -F react-app
    - stage: deployment
      before_deploy:
        - echo hello