sudo: required
language: minimal
services:
  - postgresql
  - redis-server
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
before_install:
  - export $(cat .env.ci | xargs)
    printenv
  - psql -c 'create database ${PG_TEST_DATABASE};' -U postgres
  - docker-compose -f docker-compose.yml up -d --remove-orphans --build
  - docker ps
  - docker network ls
  - docker network inspect dwh_default
  - docker run -it --env-file .env.ci --network host dwh_migrator mvn exec:java -Dspring.profiles.active=integration-test

script:
  - docker run -it --env-file .env.ci --network host dwh_common mvn install -Dspring.profiles.active=integration-test
  #- docker run -it --env-file .env.ci --network host dwh_importer mvn install -Dspring.profiles.active=integration-test

#deploy:
#  provider: script
#  script: bash ./deploy.sh
#  on:
#    branch: master