sudo: required
language: java
services:
  - postgresql
  - redis-server
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
cache:
  directories:
    - "$HOME/.cache"
install:
  - export $(cat .env.ci | xargs)
  - psql -c 'drop database if exists dwhtest;' -U postgres
  - psql -c 'create database dwhtest;' -U postgres
  - mvn -ntp clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - pwd
  - ls -la
  - java -Dspring.profiles.active=integration-test -jar ./migrator/target/application.jar
  - echo "aaa"
script:
  - echo "bbb"
  - mvn -ntp test
deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
  on:
    branch: develop
#    tags: true

#deploy:
#  provider: script
#  script: bash ./deploy.sh
#  on:
#    branch: master

