sudo: required
services:
  - postgresql
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
before_install:
  - psql -c 'create database dwhtest;' -U postgres
  - docker -v
  - docker-compose -v
  - cat /etc/hosts
  - docker-compose -f docker-compose.yml up -d --remove-orphans --build
  - docker ps
  - docker network ls
  - docker network inspect dwh_default
  - docker run -it --env-file .env.ci --network host dwh_migrator mvn exec:java -Dspring.profiles.active=integration-test

script:
  - echo "hello"
  - docker run -it --env-file .env.ci --network host dwh_common mvn install -Dspring.profiles.active=integration-test

#deploy:
#  provider: script
#  script: bash ./deploy.sh
#  on:
#    branch: master