sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
before_install:
  - sudo service postgresql stop
  - docker-compose -f docker-compose.yml up -d --remove-orphans --build
  - docker ps
  - docker run -it --env-file .env.ci dwh_migrator mvn exec:java -Dspring.profiles.active=integration-test

script:
  - echo "hello"

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master