sudo: required
language: java
jdk:
  - openjdk8

env:
  global:
    - PGPORT=30002
    - PGHOST=localhost

addons:
  postgresql: "10.3"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

before_script:
  - psql -c 'create database dwh-test' -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'admin217';" -U postgres


script: mvn clean install -DskipTests=false