sudo: required
language: java
services:
  - postgresql
  - redis-server
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
cache:
  directories:
    - "$HOME/.cache"
install:
  - export $(cat .env.ci | xargs)
  - env
  - psql -c 'create database dwhtest;' -U postgres
  - mvn -ntp install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn -ntp exec:java -pl migrator -Dspring.profiles.active=integration-test
script:
  - mvn test
deploy:
  provider: script
  script: "cp .mvn/settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    branch: develop
#    tags: true

#deploy:
#  provider: script
#  script: bash ./deploy.sh
#  on:
#    branch: master

