version: '3.7'
services:
  migrator:
    build:
      dockerfile: migrator/Dockerfile
      context: .
    volumes:
      - type: volume
        source: mavenrepo
        target: /root/.m2
  common:
    build:
      dockerfile: common/Dockerfile
      context: .
    volumes:
      - type: volume
        source: mavenrepo
        target: /root/.m2
    depends_on:
      - migrator
  importer:
    build:
      dockerfile: importer/Dockerfile
      context: .
    volumes:
      - type: volume
        source: mavenrepo
        target: /root/.m2
    depends_on:
      - common
volumes:
  mavenrepo: