version: '3.1'
services:
#  proxy:
#    image: nginx:alpine
#    container_name: proxy
#    ports:
#      - 8081:80
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  db:
    image: postgres:10.3
    container_name: db
    volumes:
    - ./.db/pg.conf:/etc/postgresql/postgresql.conf
    - ./.db/seeds:/.db/seeds
    ports:
    - 30001:5432
    environment:
      POSTGRES_DB: dwh-dev
      POSTGRES_USER: dwh-dev
      POSTGRES_PASSWORD: dwh-dev
  db-test:
    image: postgres:10.3
    container_name: db-test
    volumes:
    - ./.db/pg.conf:/etc/postgresql/postgresql.conf
    - ./.db/seeds:/.db/seeds
    ports:
    - 30002:5432
    environment:
      POSTGRES_DB: dwh-test
      POSTGRES_USER: dwh-test
      POSTGRES_PASSWORD: dwh-test
#  redis:
#    image: redis:4.0.5-alpine
#    container_name: redis
#    ports:
#      - "6379:6379"
#    command: ["redis-server", "--appendonly", "yes"]