version: '3.7'
services:
  migrator:
    build:
      dockerfile: migrator/Dockerfile
      context: .
  common:
    build:
      dockerfile: common/Dockerfile
      context: .
    depends_on:
      - migrator
  importer:
    build:
      dockerfile: importer/Dockerfile
      context: .
    depends_on:
      - common