version: '3.1'
services:

#  web:
#    build:
#      context: ./
#      dockerfile: /web/Dockerfile
#    ports:
#    - 8080:8080

  db:
    image: postgres:10.3
    volumes:
    - ./.db/pg.conf:/etc/postgresql/postgresql.conf
    - ./.db/seeds:/.db/seeds
    ports:
    - 30001:5432
    environment:
      POSTGRES_USER: tenant1
      POSTGRES_DB: tenant1
      POSTGRES_PASSWORD: password1

volumes:
  maven-repo:
    driver: local