spring:
  datasource:
    url: jdbc:postgresql://localhost:30001/dwh-dev
    username: dwh-dev
    password: dwh-dev
  flyway:
    baseline-version: 1
    enabled: false
---
spring:
  profiles: unit-test
  datasource:
    url: jdbc:postgresql://localhost:30002/dwh-dev
    username: dwh-dev
    password: dwh-dev