spring:
  profiles:
    active: development
  datasource:
    url: jdbc:postgresql://localhost:30001/tenant1
    username: tenant1
    password: password1
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
    baseline-version: 1
logging:
  level:
    root: info
  #file: ./../logs/dwh.log
dwh:
  property: prodvalue
