spring:
  profiles:
    active: development
  datasource:
    #url: jdbc:postgresql://localhost:30001/tenant1
    url: jdbc:postgresql://db:5432/tenant1
    username: tenant1
    password: password1
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    root: info
  #file: ./../logs/dwh.log
dwh:
  property: prodvalue
