server.port: 3001
spring:
  datasource:
    url: jdbc:postgresql://localhost:30001/dwh-dev
    username: dwh-dev
    password: dwh-dev
    hikari:
      minimum-idle: 5
      maximum-pool-size: 12
  jpa:
    properties:
      hibernate:
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        jdbc.lob.non_contextual_creation: true
        temp.use_jdbc_metadata_defaults: false
    database-platform: org.bmsource.dwh.common.db.CustomPostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    baseline-version: 1
  servlet:
    multipart:
      enabled: false
  redis:
    host: localhost
    port: 6379

---

spring:
  profiles: unit-test
  datasource:
    url: jdbc:h2:mem:myDb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.bmsource.dwh.common.db.CustomPostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  flyway:
    baseline-version: 1


---

spring:
  profiles: integration-test
  datasource:
    url: jdbc:postgresql://localhost:30002/dwh-test
    username: dwh-test
    password: dwh-test
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10